# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate_post_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratePostDialog(object):
    def setupUi(self, GeneratePostDialog):
        GeneratePostDialog.setObjectName("GeneratePostDialog")
        GeneratePostDialog.resize(528, 291)
        GeneratePostDialog.setMinimumSize(QtCore.QSize(528, 291))
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratePostDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subject_vertical_layout = QtWidgets.QVBoxLayout()
        self.subject_vertical_layout.setObjectName("subject_vertical_layout")
        self.subject_label = QtWidgets.QLabel(GeneratePostDialog)
        self.subject_label.setObjectName("subject_label")
        self.subject_vertical_layout.addWidget(self.subject_label)
        self.subject_line_edit = QtWidgets.QLineEdit(GeneratePostDialog)
        self.subject_line_edit.setObjectName("subject_line_edit")
        self.subject_vertical_layout.addWidget(self.subject_line_edit)
        self.verticalLayout.addLayout(self.subject_vertical_layout)
        self.keywords_vertical_layout = QtWidgets.QVBoxLayout()
        self.keywords_vertical_layout.setObjectName("keywords_vertical_layout")
        self.keywords_label = QtWidgets.QLabel(GeneratePostDialog)
        self.keywords_label.setObjectName("keywords_label")
        self.keywords_vertical_layout.addWidget(self.keywords_label)
        self.keywords_line_edit = QtWidgets.QLineEdit(GeneratePostDialog)
        self.keywords_line_edit.setObjectName("keywords_line_edit")
        self.keywords_vertical_layout.addWidget(self.keywords_line_edit)
        self.verticalLayout.addLayout(self.keywords_vertical_layout)
        self.output_type_vertical_layout = QtWidgets.QVBoxLayout()
        self.output_type_vertical_layout.setObjectName("output_type_vertical_layout")
        self.output_type_label = QtWidgets.QLabel(GeneratePostDialog)
        self.output_type_label.setObjectName("output_type_label")
        self.output_type_vertical_layout.addWidget(self.output_type_label)
        self.output_type_combo_box = QtWidgets.QComboBox(GeneratePostDialog)
        self.output_type_combo_box.setObjectName("output_type_combo_box")
        self.output_type_combo_box.addItem("")
        self.output_type_combo_box.addItem("")
        self.output_type_combo_box.addItem("")
        self.output_type_combo_box.addItem("")
        self.output_type_vertical_layout.addWidget(self.output_type_combo_box)
        self.verticalLayout.addLayout(self.output_type_vertical_layout)
        self.output_dir_vertical_layout = QtWidgets.QVBoxLayout()
        self.output_dir_vertical_layout.setObjectName("output_dir_vertical_layout")
        self.output_dir_label = QtWidgets.QLabel(GeneratePostDialog)
        self.output_dir_label.setObjectName("output_dir_label")
        self.output_dir_vertical_layout.addWidget(self.output_dir_label)
        self.output_dir_horizontal_layout = QtWidgets.QHBoxLayout()
        self.output_dir_horizontal_layout.setObjectName("output_dir_horizontal_layout")
        self.output_dir_line_edit = QtWidgets.QLineEdit(GeneratePostDialog)
        self.output_dir_line_edit.setReadOnly(True)
        self.output_dir_line_edit.setClearButtonEnabled(False)
        self.output_dir_line_edit.setObjectName("output_dir_line_edit")
        self.output_dir_horizontal_layout.addWidget(self.output_dir_line_edit)
        self.explorer_button = QtWidgets.QToolButton(GeneratePostDialog)
        self.explorer_button.setObjectName("explorer_button")
        self.output_dir_horizontal_layout.addWidget(self.explorer_button)
        self.output_dir_vertical_layout.addLayout(self.output_dir_horizontal_layout)
        self.verticalLayout.addLayout(self.output_dir_vertical_layout)
        self.footer_horizontal_layout = QtWidgets.QHBoxLayout()
        self.footer_horizontal_layout.setObjectName("footer_horizontal_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footer_horizontal_layout.addItem(spacerItem)
        self.exec_button = QtWidgets.QPushButton(GeneratePostDialog)
        self.exec_button.setObjectName("exec_button")
        self.footer_horizontal_layout.addWidget(self.exec_button)
        self.verticalLayout.addLayout(self.footer_horizontal_layout)

        self.retranslateUi(GeneratePostDialog)
        QtCore.QMetaObject.connectSlotsByName(GeneratePostDialog)

    def retranslateUi(self, GeneratePostDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneratePostDialog.setWindowTitle(_translate("GeneratePostDialog", "Generate Post (*.md, *.txt, *.html)"))
        self.subject_label.setText(_translate("GeneratePostDialog", "Subject"))
        self.keywords_label.setText(_translate("GeneratePostDialog", "Keywords"))
        self.keywords_line_edit.setPlaceholderText(_translate("GeneratePostDialog", "keyword, next"))
        self.output_type_label.setText(_translate("GeneratePostDialog", "Type"))
        self.output_type_combo_box.setItemText(0, _translate("GeneratePostDialog", "Select..."))
        self.output_type_combo_box.setItemText(1, _translate("GeneratePostDialog", "Plain Text"))
        self.output_type_combo_box.setItemText(2, _translate("GeneratePostDialog", "Markdown"))
        self.output_type_combo_box.setItemText(3, _translate("GeneratePostDialog", "HTML"))
        self.output_dir_label.setText(_translate("GeneratePostDialog", "Output"))
        self.explorer_button.setText(_translate("GeneratePostDialog", "..."))
        self.exec_button.setText(_translate("GeneratePostDialog", "Executar"))
